version: "3.9"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8501}:8501"
    environment:
      PORT: 8501
    volumes:
      - "./temp_audio:/app/temp_audio"
      - "./temp_component:/app/temp_component"
    labels:
      - traefik.enable=true
      - traefik.http.routers.textaudio.rule=Host(`texttoaudio.shopabcquocdat.xyz`)
      - traefik.http.routers.textaudio.entrypoints=web,websecure
      - traefik.http.routers.textaudio.tls=true
      - traefik.http.routers.textaudio.tls.certresolver=mytlschallenge
      - traefik.http.services.textaudio.loadbalancer.server.port=8501
    restart: unless-stopped

    networks:
      - root_default
      - textaudion8n_default

networks:
  root_default:
    external: true  
  textaudion8n_default:
    external: true  